#!/bin/bash

# This script lets the user to install all essential and core things for arch linux"
# Usage: chmod +x init-setup.sh && ./init-setup.sh
echo "Starting initial setup for Arch Linux..."
echo "Updating package database and upgrading existing packages..."
sudo pacman -Syu --noconfirm
echo "System updated."
echo "Installing AUR helper (yay)..."
sudo pacman -S git --noconfirm
git clone https://aur.archlinux.org/yay.git
cd yay
echo "From here, make sure that you have pressed enter if prompted during the build process."
makepkg -si --noconfirm
echo "AUR helper (yay) installed."
echo "Installing essential packages..."
ESSENTIAL_PACKAGES=(base-devel git vim wget curl aria2 htop neofetch google-chrome firefox brave-bin vlc mpv telegram-desktop-bin extension-manager code zsh)
for package in "${ESSENTIAL_PACKAGES[@]}"; do
    echo "Installing $package..."
    yay -S --noconfirm "$package"
done
echo "Essential packages installed."

echo "Changing default shell to zsh..."
chsh -s $(which zsh)   
echo "Default shell changed to zsh."
echo "If you want to change the shell of your root user, run 'sudo chsh -s $(which zsh)' separately."
echo "Initial setup for Arch Linux completed."
